# Generated by Django 3.1.7 on 2021-02-24 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(max_length=200)),
                ('image_file', models.ImageField(upload_to='images/')),
                ('date_taken', models.DateTimeField(verbose_name='date taken')),
                ('date_db', models.DateTimeField(verbose_name='date arrived')),
            ],
        ),
    ]
