# Generated by Django 3.1.7 on 2021-02-24 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploader', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='title',
            field=models.TextField(default='Iwojima', max_length=200),
        ),
    ]
