# Generated by Django 3.1.7 on 2021-02-24 11:06

from django.db import migrations, models
import exiffield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('uploader', '0003_auto_20210224_1035'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='exif',
            field=exiffield.fields.ExifField(default={}, editable=False),
        ),
        migrations.AlterField(
            model_name='image',
            name='date_db',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='image',
            name='date_taken',
            field=models.DateTimeField(editable=False, null=True),
        ),
    ]
