# Generated by Django 3.1.7 on 2021-02-24 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploader', '0004_auto_20210224_1206'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='exif',
        ),
        migrations.AlterField(
            model_name='image',
            name='date_taken',
            field=models.DateTimeField(null=True),
        ),
    ]
